# IMPALA with V-trace for Atari.
#
# Espeholt et al., ICML 2018, "IMPALA: Scalable Distributed Deep-RL with
# Importance Weighted Actor-Learner Architectures" (https://arxiv.org/abs/1802.01561).
#
# IMPALA makes two contributions and they are separable:
#
#   1. a *systems* contribution — hundreds of actors generating trajectories
#      asynchronously against a single learner, which is what buys the 250k
#      frames/s the paper reports; and
#   2. an *algorithmic* contribution — V-trace, the off-policy correction that
#      makes (1) sound. Actors always hold stale weights, so the trajectories
#      arriving at the learner were generated by a policy mu that is not the
#      learner's current pi. V-trace reweights them with truncated importance
#      ratios and stays a contraction.
#
# This file is (2), on this repository's synchronous vectorised rollout. The
# V-trace transcription is from facebookresearch/torchbeast
# (https://github.com/facebookresearch/torchbeast, `torchbeast/core/vtrace.py`,
# Apache 2.0), which is itself a direct PyTorch port of DeepMind's original
# `scalable_agent/vtrace.py`; the learner losses follow `monobeast.py`.
#
# A synchronous learner has no natural staleness, so at the defaults
# (`--actor-lag 0 --update-epochs 1 --num-minibatches 1`) the behaviour policy
# *is* the target policy, every rho is exactly 1, and V-trace collapses to
# ordinary n-step returns. That is not a bug and it is not a straw man: it is
# what IMPALA reduces to when the asynchrony is removed, and
# `tests/test_impala_equivalence.py` pins the reduction. Three knobs put the
# off-policyness back:
#
#   --actor-lag K       act with learner weights from K updates ago, which is
#                       what an asynchronous actor pool produces;
#   --update-epochs E   reuse each rollout E times, so passes 2..E are off-policy;
#   --num-minibatches M split the rollout, so minibatches 2..M are off-policy.
#
# The last two are how PPO creates off-policy data too — the difference is that
# PPO handles it with a clipping heuristic while V-trace handles it with a
# correction that has a fixed point.
#
# Two details worth stating because they are easy to get wrong:
#
#   * torchbeast's losses are `torch.sum`, not `torch.mean`. With unroll 80 and
#     batch 32 that is a factor of 2560 folded into the learning rate. This port
#     keeps `sum` (`--loss-reduction sum`, the default) so torchbeast's
#     `learning_rate=0.00048` and `grad_norm_clipping=40` mean what they mean.
#   * `discounts = (1 - done) * gamma`, and the done that belongs to step t is
#     the one *produced by* step t.
import json
import os
import random
import sys
import time
from dataclasses import dataclass

import gymnasium as gym
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import tyro
from torch.distributions.categorical import Categorical
from torch.utils.tensorboard import SummaryWriter

try:
    import envpool
except ImportError:
    envpool = None

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from cule_env import (
    done_tensor,
    frame_stack_observation,
    grayscale_observation,
    make_cule_env,
    resolve_cule_device,
    step_env,
    to_numpy,
    to_tensor,
)

from cleanrl_utils.atari_wrappers import (  # isort:skip
    ClipRewardEnv,
    EpisodicLifeEnv,
    FireResetEnv,
    MaxAndSkipEnv,
    NoopResetEnv,
)
from cleanrl_utils.episode_stats import EpisodeStats  # isort:skip


@dataclass
class Args:
    exp_name: str = os.path.basename(__file__)[: -len(".py")]
    """the name of this experiment"""
    seed: int = 1
    """seed of the experiment"""
    torch_deterministic: bool = True
    """if toggled, `torch.backends.cudnn.deterministic=False`"""
    cuda: bool = True
    """if toggled, cuda will be enabled by default"""
    track: bool = False
    """if toggled, this experiment will be tracked with Weights and Biases"""
    wandb_project_name: str = "cleanRL"
    """the wandb's project name"""
    wandb_entity: str = None
    """the entity (team) of wandb's project"""
    capture_video: bool = False
    """whether to capture videos of the agent performances (check out `videos` folder)"""
    env_backend: str = "gymnasium"
    """environment backend: `gymnasium`, `cule`, or `envpool`"""
    cule_device: str = "auto"
    """device for the CuLE backend: `auto`, `cpu`, or a CUDA device string"""

    # Algorithm specific arguments
    env_id: str = "BreakoutNoFrameskip-v4"
    """the id of the environment"""
    total_timesteps: int = 10000000
    """total timesteps of the experiments"""
    learning_rate: float = 0.00048
    """the learning rate of the optimizer (torchbeast default)"""
    num_envs: int = 32
    """the number of parallel game environments (torchbeast's `batch_size`)"""
    num_steps: int = 80
    """rollout length per environment (torchbeast's `unroll_length`)"""
    anneal_lr: bool = True
    """Toggle linear learning rate annealing, as in torchbeast's LambdaLR"""
    gamma: float = 0.99
    """the discount factor gamma (torchbeast's `discounting`)"""
    ent_coef: float = 0.0006
    """coefficient of the entropy (torchbeast's `entropy_cost`)"""
    vf_coef: float = 0.5
    """coefficient of the value function (torchbeast's `baseline_cost`)"""
    max_grad_norm: float = 40.0
    """the maximum norm for the gradient clipping (torchbeast's `grad_norm_clipping`)"""
    rmsprop_alpha: float = 0.99
    """RMSProp decay rate"""
    rmsprop_eps: float = 0.01
    """RMSProp epsilon. Note this is 1e-2, not the 1e-5/1e-8 usual elsewhere"""
    rmsprop_momentum: float = 0.0
    """RMSProp momentum"""

    clip_rho_threshold: float = 1.0
    """rho-bar: caps the importance ratio in the value target, bounding its bias"""
    clip_pg_rho_threshold: float = 1.0
    """rho-bar for the policy gradient advantage"""
    loss_reduction: str = "sum"
    """`sum` (torchbeast) or `mean`. `sum` folds T*B into the learning rate"""

    actor_lag: int = 0
    """learner updates of staleness in the behaviour policy; 0 is fully on-policy"""
    update_epochs: int = 1
    """passes over each rollout; >1 makes later passes off-policy"""
    num_minibatches: int = 1
    """environment-wise minibatches per pass; >1 makes later minibatches off-policy"""
    encoder: str = "nature"
    """`nature` (IMPALA's shallow model) or `impala` (the 15-layer residual model)"""

    # to be filled in runtime
    batch_size: int = 0
    """the batch size (computed in runtime)"""
    num_iterations: int = 0
    """the number of iterations (computed in runtime)"""

    solve_window: int = 100
    """episodes averaged when reporting the running return"""

    benchmark: bool = False
    """run a fixed warmup/measurement window and print a JSON benchmark result"""
    benchmark_warmup_iterations: int = 3
    """full training iterations excluded from benchmark timing"""
    benchmark_measure_iterations: int = 10
    """full training iterations included in benchmark timing"""


def make_env(env_id, seed, idx, capture_video, run_name):
    def thunk():
        if capture_video and idx == 0:
            env = gym.make(env_id, render_mode="rgb_array")
            env = gym.wrappers.RecordVideo(env, f"videos/{run_name}")
        else:
            env = gym.make(env_id)
        env = gym.wrappers.RecordEpisodeStatistics(env)
        env = NoopResetEnv(env, noop_max=30)
        env = MaxAndSkipEnv(env, skip=4)
        env = EpisodicLifeEnv(env)
        if "FIRE" in env.unwrapped.get_action_meanings():
            env = FireResetEnv(env)
        env = ClipRewardEnv(env)
        env = gym.wrappers.ResizeObservation(env, (84, 84))
        env = grayscale_observation(env)
        env = frame_stack_observation(env, 4)
        env.action_space.seed(seed)
        return env

    return thunk


class RecordEpisodeStatistics(gym.Wrapper):
    """Expose EnvPool spaces and full-game statistics to the trainer."""

    def __init__(self, env):
        super().__init__(env)
        self.num_envs = getattr(env, "num_envs", 1)
        self.single_action_space = getattr(env, "single_action_space", env.action_space)
        self.single_observation_space = getattr(env, "single_observation_space", env.observation_space)

    def reset(self, **kwargs):
        observations = super().reset(**kwargs)
        self.episode_returns = np.zeros(self.num_envs, dtype=np.float32)
        self.episode_lengths = np.zeros(self.num_envs, dtype=np.int32)
        self.returned_episode_returns = np.zeros(self.num_envs, dtype=np.float32)
        self.returned_episode_lengths = np.zeros(self.num_envs, dtype=np.int32)
        return observations

    def step(self, action):
        result = super().step(action)
        if len(result) == 5:
            observations, rewards, terminations, truncations, infos = result
            dones = np.logical_or(terminations, truncations)
        else:
            observations, rewards, dones, infos = result
        self.episode_returns += infos["reward"]
        self.episode_lengths += 1
        self.returned_episode_returns[:] = self.episode_returns
        self.returned_episode_lengths[:] = self.episode_lengths
        game_over = np.logical_and(dones, np.asarray(infos["lives"]) == 0)
        self.episode_returns *= 1 - game_over
        self.episode_lengths *= 1 - game_over
        infos["r"] = self.returned_episode_returns
        infos["l"] = self.returned_episode_lengths
        if len(result) == 5:
            return observations, rewards, terminations, truncations, infos
        return observations, rewards, dones, infos


def completed_episode_infos(infos, dones):
    """Normalize per-backend episode statistics to the `final_info` format."""
    if "final_info" in infos:
        return infos
    if "r" in infos:  # EnvPool RecordEpisodeStatistics
        game_over = to_numpy(dones).astype(bool) & (np.asarray(infos["lives"]) == 0)
        if game_over.any():
            return {
                "final_info": [
                    {"episode": {"r": float(infos["r"][index]), "l": int(infos["l"][index])}}
                    for index in np.flatnonzero(game_over)
                ]
            }
    return {}


# ---------------------------------------------------------------------------
# V-trace
#
# Transcribed from torchbeast's `core/vtrace.py`, which is DeepMind's
# `scalable_agent/vtrace.py` ported to PyTorch. Kept as free functions on
# [T, B] tensors so the tests can drive them directly.
# ---------------------------------------------------------------------------

def action_log_probs(policy_logits, actions):
    """log pi(a_t | x_t) for the taken actions, on [T, B, A] logits."""
    return -F.nll_loss(
        F.log_softmax(torch.flatten(policy_logits, 0, -2), dim=-1),
        torch.flatten(actions),
        reduction="none",
    ).view_as(actions)


@torch.no_grad()
def vtrace_from_importance_weights(
    log_rhos,
    discounts,
    rewards,
    values,
    bootstrap_value,
    clip_rho_threshold=1.0,
    clip_pg_rho_threshold=1.0,
):
    """V-trace targets `vs` and policy-gradient advantages, from log(pi/mu).

    Equation 1 of the IMPALA paper:

        v_s = V(x_s) + sum_t gamma^(t-s) (prod_{i=s}^{t-1} c_i) delta_t V

    with `delta_t V = rho_t (r_t + gamma V(x_{t+1}) - V(x_t))`,
    `rho_t = min(rho_bar, pi/mu)` and `c_i = min(1, pi/mu)`. Written as the
    backward recursion

        vs_minus_v_xs[t] = delta_t V + gamma * c_t * vs_minus_v_xs[t+1]

    which is the form the reference implements.

    `rho_bar` bounds the bias of the fixed point (which policy V-trace converges
    to); `c_bar` — hard-coded to 1 here as in every reference — bounds the
    variance of the product of traces.
    """
    rhos = torch.exp(log_rhos)
    clipped_rhos = rhos if clip_rho_threshold is None else torch.clamp(rhos, max=clip_rho_threshold)
    cs = torch.clamp(rhos, max=1.0)

    values_t_plus_1 = torch.cat([values[1:], bootstrap_value.unsqueeze(0)], dim=0)
    deltas = clipped_rhos * (rewards + discounts * values_t_plus_1 - values)

    acc = torch.zeros_like(bootstrap_value)
    result = []
    for t in range(discounts.shape[0] - 1, -1, -1):
        acc = deltas[t] + discounts[t] * cs[t] * acc
        result.append(acc)
    result.reverse()
    vs = torch.stack(result) + values

    # The policy-gradient advantage bootstraps off `vs`, not off `values`.
    broadcasted_bootstrap = torch.ones_like(vs[0]) * bootstrap_value
    vs_t_plus_1 = torch.cat([vs[1:], broadcasted_bootstrap.unsqueeze(0)], dim=0)
    clipped_pg_rhos = rhos if clip_pg_rho_threshold is None else torch.clamp(rhos, max=clip_pg_rho_threshold)
    pg_advantages = clipped_pg_rhos * (rewards + discounts * vs_t_plus_1 - values)
    return vs, pg_advantages


def vtrace_from_logits(
    behavior_policy_logits,
    target_policy_logits,
    actions,
    discounts,
    rewards,
    values,
    bootstrap_value,
    clip_rho_threshold=1.0,
    clip_pg_rho_threshold=1.0,
):
    """V-trace for softmax policies; returns `(vs, pg_advantages, log_rhos)`."""
    target_log_probs = action_log_probs(target_policy_logits, actions)
    behavior_log_probs = action_log_probs(behavior_policy_logits, actions)
    log_rhos = target_log_probs - behavior_log_probs
    vs, pg_advantages = vtrace_from_importance_weights(
        log_rhos=log_rhos,
        discounts=discounts,
        rewards=rewards,
        values=values,
        bootstrap_value=bootstrap_value,
        clip_rho_threshold=clip_rho_threshold,
        clip_pg_rho_threshold=clip_pg_rho_threshold,
    )
    return vs, pg_advantages, log_rhos


# ---------------------------------------------------------------------------
# learner losses (monobeast.py)
# ---------------------------------------------------------------------------

def compute_baseline_loss(advantages, reduction="sum"):
    """0.5 * ||vs - V||^2. torchbeast sums; `mean` is offered for comparability."""
    squared = advantages**2
    return 0.5 * (squared.sum() if reduction == "sum" else squared.mean())


def compute_entropy_loss(logits, reduction="sum"):
    """*Negative* entropy — a loss, so minimising it maximises entropy."""
    policy = F.softmax(logits, dim=-1)
    log_policy = F.log_softmax(logits, dim=-1)
    per_step = (policy * log_policy).sum(dim=-1)
    return per_step.sum() if reduction == "sum" else per_step.mean()


def compute_policy_gradient_loss(logits, actions, advantages, reduction="sum"):
    """`sum(-log pi(a|x) * A)`, with the advantage treated as data."""
    cross_entropy = F.nll_loss(
        F.log_softmax(torch.flatten(logits, 0, -2), dim=-1),
        target=torch.flatten(actions),
        reduction="none",
    ).view_as(advantages)
    weighted = cross_entropy * advantages.detach()
    return weighted.sum() if reduction == "sum" else weighted.mean()


def layer_init(layer, std=np.sqrt(2), bias_const=0.0):
    torch.nn.init.orthogonal_(layer.weight, std)
    torch.nn.init.constant_(layer.bias, bias_const)
    return layer


# The residual encoder from the IMPALA paper's "deep" model, in the widths the
# paper uses. Same module as `qdagger_dqn_atari_impalacnn.py` carries.
class ResidualBlock(nn.Module):
    def __init__(self, channels):
        super().__init__()
        self.conv0 = nn.Conv2d(channels, channels, 3, padding=1)
        self.conv1 = nn.Conv2d(channels, channels, 3, padding=1)

    def forward(self, x):
        inputs = x
        x = F.relu(x)
        x = self.conv0(x)
        x = F.relu(x)
        x = self.conv1(x)
        return x + inputs


class ConvSequence(nn.Module):
    def __init__(self, input_shape, out_channels):
        super().__init__()
        self._input_shape = input_shape
        self._out_channels = out_channels
        self.conv = nn.Conv2d(input_shape[0], out_channels, 3, padding=1)
        self.res_block0 = ResidualBlock(out_channels)
        self.res_block1 = ResidualBlock(out_channels)

    def forward(self, x):
        x = self.conv(x)
        x = F.max_pool2d(x, kernel_size=3, stride=2, padding=1)
        x = self.res_block0(x)
        return self.res_block1(x)

    def get_output_shape(self):
        _c, h, w = self._input_shape
        return (self._out_channels, (h + 1) // 2, (w + 1) // 2)


class Agent(nn.Module):
    """Shared torso, a policy-logit head and a scalar baseline head."""

    def __init__(self, envs, encoder="nature"):
        super().__init__()
        self.encoder = encoder
        if encoder == "nature":
            self.network = nn.Sequential(
                layer_init(nn.Conv2d(4, 32, 8, stride=4)),
                nn.ReLU(),
                layer_init(nn.Conv2d(32, 64, 4, stride=2)),
                nn.ReLU(),
                layer_init(nn.Conv2d(64, 64, 3, stride=1)),
                nn.ReLU(),
                nn.Flatten(),
                layer_init(nn.Linear(64 * 7 * 7, 512)),
                nn.ReLU(),
            )
        elif encoder == "impala":
            shape = envs.single_observation_space.shape
            layers = []
            for out_channels in (16, 32, 32):
                sequence = ConvSequence(shape, out_channels)
                shape = sequence.get_output_shape()
                layers.append(sequence)
            layers += [nn.ReLU(), nn.Flatten(), layer_init(nn.Linear(int(np.prod(shape)), 512)), nn.ReLU()]
            self.network = nn.Sequential(*layers)
        else:
            raise ValueError(f"unsupported encoder: {encoder}")
        self.actor = layer_init(nn.Linear(512, envs.single_action_space.n), std=0.01)
        self.critic = layer_init(nn.Linear(512, 1), std=1)

    def forward(self, x):
        hidden = self.network(x / 255.0)
        return self.actor(hidden), self.critic(hidden).squeeze(-1)

    def get_value(self, x):
        return self.forward(x)[1]

    def get_action_logits_and_value(self, x):
        logits, value = self.forward(x)
        return Categorical(logits=logits).sample(), logits, value


def build_optimizer(parameters, args):
    """torchbeast's optimiser: RMSProp at eps=1e-2, which is unusually large."""
    return optim.RMSprop(
        parameters,
        lr=args.learning_rate,
        momentum=args.rmsprop_momentum,
        eps=args.rmsprop_eps,
        alpha=args.rmsprop_alpha,
    )


def torchbeast_lr_fraction(consumed_steps, total_timesteps):
    """torchbeast's `lr_lambda`: `1 - min(epoch * T * B, total) / total`."""
    return 1.0 - min(consumed_steps, total_timesteps) / total_timesteps


if __name__ == "__main__":
    process_start = time.perf_counter()
    args = tyro.cli(Args)
    if args.num_envs < 1:
        raise ValueError("num_envs must be positive")
    if args.num_steps < 1:
        raise ValueError("num_steps must be positive")
    if args.num_minibatches < 1:
        raise ValueError("num_minibatches must be positive")
    if args.num_envs % args.num_minibatches:
        raise ValueError("num_envs must be divisible by num_minibatches")
    if args.update_epochs < 1:
        raise ValueError("update_epochs must be positive")
    if args.actor_lag < 0:
        raise ValueError("actor_lag cannot be negative")
    if args.loss_reduction not in ("sum", "mean"):
        raise ValueError("loss_reduction must be `sum` or `mean`")
    if args.benchmark_warmup_iterations < 0:
        raise ValueError("benchmark_warmup_iterations cannot be negative")
    if args.benchmark_measure_iterations < 1:
        raise ValueError("benchmark_measure_iterations must be positive")
    args.batch_size = int(args.num_envs * args.num_steps)
    args.num_iterations = args.total_timesteps // args.batch_size
    if args.benchmark:
        args.num_iterations = args.benchmark_warmup_iterations + args.benchmark_measure_iterations
    envs_per_minibatch = args.num_envs // args.num_minibatches
    run_name = f"{args.env_id}__{args.exp_name}__{args.seed}__{int(time.time())}"
    if args.track:
        import wandb

        wandb.init(
            project=args.wandb_project_name,
            entity=args.wandb_entity,
            sync_tensorboard=True,
            config=vars(args),
            name=run_name,
            monitor_gym=True,
            save_code=True,
        )
    writer = None if args.benchmark else SummaryWriter(f"runs/{run_name}")
    if writer is not None:
        writer.add_text(
            "hyperparameters",
            "|param|value|\n|-|-|\n%s" % ("\n".join([f"|{key}|{value}|" for key, value in vars(args).items()])),
        )

    # TRY NOT TO MODIFY: seeding
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.backends.cudnn.deterministic = args.torch_deterministic

    device = torch.device("cuda" if torch.cuda.is_available() and args.cuda else "cpu")
    if device.type == "cuda":
        torch.cuda.reset_peak_memory_stats(device)

    # env setup
    if args.env_backend == "cule":
        env_device = resolve_cule_device(args.cule_device, device, args.num_envs)
        envs = make_cule_env(args.env_id, args.num_envs, env_device, args.seed, args.capture_video)
    elif args.env_backend == "envpool":
        if envpool is None:
            raise ImportError("EnvPool backend requested; install envpool or pass --env-backend cule")
        envs = RecordEpisodeStatistics(
            envpool.make(
                args.env_id,
                env_type="gym",
                num_envs=args.num_envs,
                episodic_life=True,
                reward_clip=True,
                seed=args.seed,
            )
        )
    elif args.env_backend == "gymnasium":
        envs = gym.vector.SyncVectorEnv(
            [make_env(args.env_id, args.seed + i, i, args.capture_video, run_name) for i in range(args.num_envs)],
        )
    else:
        raise ValueError(f"unsupported environment backend: {args.env_backend}")
    assert isinstance(envs.single_action_space, gym.spaces.Discrete), "only discrete action space is supported"

    agent = Agent(envs, args.encoder).to(device)
    # The behaviour policy. IMPALA's actors hold weights the learner has already
    # moved past; `--actor-lag K` reproduces that by refreshing this copy only
    # every K+1 learner updates. At K=0 it tracks the learner exactly and the
    # run is on-policy.
    behaviour_agent = Agent(envs, args.encoder).to(device)
    behaviour_agent.load_state_dict(agent.state_dict())
    for parameter in behaviour_agent.parameters():
        parameter.requires_grad_(False)
    optimizer = build_optimizer(agent.parameters(), args)

    # ALGO Logic: Storage setup
    obs = torch.zeros((args.num_steps, args.num_envs) + envs.single_observation_space.shape).to(device)
    actions = torch.zeros((args.num_steps, args.num_envs), dtype=torch.long).to(device)
    behaviour_logits = torch.zeros((args.num_steps, args.num_envs, int(envs.single_action_space.n))).to(device)
    rewards = torch.zeros((args.num_steps, args.num_envs)).to(device)
    # `next_dones[t]` is the flag produced *by* step t.
    next_dones = torch.zeros((args.num_steps, args.num_envs)).to(device)

    # TRY NOT TO MODIFY: start the game
    global_step = 0
    start_time = time.time()
    next_obs, _ = envs.reset(seed=args.seed)
    next_obs = to_tensor(next_obs, device)
    next_done = torch.zeros(args.num_envs).to(device)
    stats = EpisodeStats(args.solve_window)
    benchmark_start = None
    benchmark_start_step = None
    learner_updates = 0

    for iteration in range(1, args.num_iterations + 1):
        if args.benchmark and iteration == args.benchmark_warmup_iterations + 1:
            if device.type == "cuda":
                torch.cuda.synchronize(device)
            benchmark_start = time.perf_counter()
            benchmark_start_step = global_step
        if args.anneal_lr:
            frac = torchbeast_lr_fraction(global_step, args.total_timesteps)
            optimizer.param_groups[0]["lr"] = frac * args.learning_rate

        for step in range(0, args.num_steps):
            global_step += args.num_envs
            obs[step] = next_obs

            # ALGO LOGIC: act with the *behaviour* policy, and record its logits.
            with torch.no_grad():
                action, logits, _ = behaviour_agent.get_action_logits_and_value(next_obs)
            actions[step] = action
            behaviour_logits[step] = logits

            # TRY NOT TO MODIFY: execute the game and log data.
            next_obs, reward, terminations, truncations, infos = step_env(envs, action)
            next_done = done_tensor(terminations, truncations, device)
            rewards[step] = to_tensor(reward, device).view(-1)
            next_dones[step] = next_done
            next_obs = to_tensor(next_obs, device)

            stats.update(completed_episode_infos(infos, next_done), global_step, writer)

        # `discounts[t] = (1 - done_t) * gamma`, as in monobeast.
        discounts = (1.0 - next_dones) * args.gamma

        for epoch in range(args.update_epochs):
            permutation = torch.randperm(args.num_envs, device=device)
            for start in range(0, args.num_envs, envs_per_minibatch):
                env_indices = permutation[start : start + envs_per_minibatch]

                # One forward pass over the [T, B_mb] slice plus the bootstrap
                # observation, so the learner sees `num_steps + 1` states.
                mb_obs = torch.cat([obs[:, env_indices], next_obs[env_indices].unsqueeze(0)], dim=0)
                flat_logits, flat_values = agent(mb_obs.flatten(0, 1))
                target_logits = flat_logits.view(args.num_steps + 1, len(env_indices), -1)
                values = flat_values.view(args.num_steps + 1, len(env_indices))

                bootstrap_value = values[-1]
                target_logits, values = target_logits[:-1], values[:-1]

                vs, pg_advantages, log_rhos = vtrace_from_logits(
                    behavior_policy_logits=behaviour_logits[:, env_indices],
                    target_policy_logits=target_logits,
                    actions=actions[:, env_indices],
                    discounts=discounts[:, env_indices],
                    rewards=rewards[:, env_indices],
                    values=values,
                    bootstrap_value=bootstrap_value,
                    clip_rho_threshold=args.clip_rho_threshold,
                    clip_pg_rho_threshold=args.clip_pg_rho_threshold,
                )

                pg_loss = compute_policy_gradient_loss(
                    target_logits, actions[:, env_indices], pg_advantages, args.loss_reduction)
                baseline_loss = args.vf_coef * compute_baseline_loss(vs - values, args.loss_reduction)
                entropy_loss = args.ent_coef * compute_entropy_loss(target_logits, args.loss_reduction)
                total_loss = pg_loss + baseline_loss + entropy_loss

                optimizer.zero_grad()
                total_loss.backward()
                nn.utils.clip_grad_norm_(agent.parameters(), args.max_grad_norm)
                optimizer.step()
                learner_updates += 1

        # Refresh the actors. IMPALA pushes weights after every learner batch;
        # the staleness comes from the actors being mid-trajectory when it lands.
        if args.actor_lag == 0 or iteration % (args.actor_lag + 1) == 0:
            behaviour_agent.load_state_dict(agent.state_dict())

        if writer is not None:
            writer.add_scalar("charts/learning_rate", optimizer.param_groups[0]["lr"], global_step)
            writer.add_scalar("losses/total_loss", total_loss.item(), global_step)
            writer.add_scalar("losses/policy_loss", pg_loss.item(), global_step)
            writer.add_scalar("losses/baseline_loss", baseline_loss.item(), global_step)
            writer.add_scalar("losses/entropy_loss", entropy_loss.item(), global_step)
            writer.add_scalar("losses/mean_rho", log_rhos.exp().mean().item(), global_step)
            writer.add_scalar("losses/clipped_rho_frac", (log_rhos.exp() > args.clip_rho_threshold).float().mean().item(), global_step)
            print("SPS:", int(global_step / (time.time() - start_time)))
            writer.add_scalar("charts/SPS", int(global_step / (time.time() - start_time)), global_step)

    if args.benchmark:
        if device.type == "cuda":
            torch.cuda.synchronize(device)
        benchmark_end = time.perf_counter()
        measured_steps = global_step - benchmark_start_step
        measured_seconds = benchmark_end - benchmark_start
        result = {
            "algorithm": "impala",
            "actor_lag": args.actor_lag,
            "backend": args.env_backend,
            "batch_size": args.batch_size,
            "benchmark": "full_training_loop",
            "compile": False,
            "encoder": args.encoder,
            "env_id": args.env_id,
            "measure_iterations": args.benchmark_measure_iterations,
            "measured_seconds": measured_seconds,
            "measured_steps": measured_steps,
            "num_envs": args.num_envs,
            "num_minibatches": args.num_minibatches,
            "num_steps": args.num_steps,
            "peak_cuda_memory_mb": (
                torch.cuda.max_memory_allocated(device) / (1024**2) if device.type == "cuda" else 0.0
            ),
            "process_seconds": benchmark_end - process_start,
            "schema_version": 1,
            "sps": measured_steps / measured_seconds,
            "update_epochs": args.update_epochs,
            "warmup_iterations": args.benchmark_warmup_iterations,
        }
        print(f"BENCHMARK_RESULT {json.dumps(result, sort_keys=True)}", flush=True)

    envs.close()
    if writer is not None:
        writer.close()
