name: cule
channels:
        - conda-forge
dependencies:
        - python=3.12
        - pip
        - pip:
                - torch
                - torchrl==0.13.2
                - gymnasium
                - ale-py
                - numpy
                - matplotlib
                - opencv-python-headless
                - tqdm
                - psutil
                - pytz
                - tensorboard
                - cloudpickle
